name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jar-file
          path: build/libs/web-0.0.1-SNAPSHOT.jar

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            pkill -f 'java -jar' || true
            mv ./build/libs/web-0.0.1-SNAPSHOT.jar /home/ubuntu/app/web-0.0.1-SNAPSHOT.jar
            nohup java -jar /home/ubuntu/app/web-0.0.1-SNAPSHOT.jar > /home/ubuntu/app/app.log 2>&1 &