name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true  # 디버그 모드 활성화

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jar-file
          path: build/libs/web-0.0.1-SNAPSHOT.jar

      - name: Debugging Step
        run: |
          echo "Current working directory:"
          pwd
          echo "List of files in the directory:"
          ls -al
          echo "Content of environment variables:"
          printenv

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          debug: true
          script: |
            echo "Stopping any running Java applications..."
            pkill -f 'java -jar' || true
            echo "Moving JAR file to deployment directory..."
            mv ./build/libs/web-0.0.1-SNAPSHOT.jar /home/ubuntu/cpu/web-0.0.1-SNAPSHOT.jar
            echo "Starting the application..."
            nohup java -jar /home/ubuntu/cpu/web-0.0.1-SNAPSHOT.jar > /home/ubuntu/cpu/app.log 2>&1 &
            echo "Deployment script finished."
